### ISSUE TITLE
It's Alive ! tiny_bx

### ISSUE THREAD

**Issue by zignig** [cbiffle/hapenny#1]
Managed to port the  new version of the cpu to the tiny_bx board.

https://github.com/zignig/hapenny/blob/main/tinybxtestbox.py

Changed the PLL and the oversampling on the UART was turned down to 4. It compiled and uploaded onto the board running at 40Mhz. I can then connect to the FTDI and there seems to be characters echoing. Hooray!

I have been digging into risc-v and rust and managed to cobble together a runtime thing. (https://github.com/zignig/patina)

Is it possible to release the tiny-bootloader (which I assume is rust) ?

**Comment by cbiffle** [comment]
Hey zignig, it's been a while! :-)

That's slick. I'd be happy to merge that if you want -- I need to clean up all the various "test" scripts and centralize the SoC definition so I can stop copy-pasting stuff. (I've got an Icoboard image working and I'm playing with an ECP5 port to the ULX3S, so the duplication has started to become annoying.)

I, uh, did not realize that the bootloader sources were not checked in. `git status` would have revealed this to me, I suppose. I'll fix that. :-) Also the tool for interacting with the bootloader, which would make it a lot more useful.

**Comment by cbiffle** [comment]
Bootloader sources are here: https://github.com/cbiffle/hapenny/tree/main/tinyboot
Command line tool for driving the serial monitor is here: https://github.com/cbiffle/hapenny/tree/main/montool

**Comment by cbiffle** [comment]
Note that the bootloader is technically quite unsound from Rust's perspective, since it is perfectly willing to overwrite its own instructions if asked. I just got tired of maintaining the assembly version. :-)

**Comment by zignig** [comment]
thanks @cbiffle!

Will get it running. The link file for the bootloader build is going to suck, I'm going to try to lib.rs it out and have workspaces per target/board with their own link.x file , UART register mapping and a main() that is minimal. 

The bus into the soc is quite clean at the moment and the fabric is shiny very tidy... however, There exists (https://github.com/amaranth-lang/amaranth-soc) that has some memory maps , CSR , etc. The cool thing about it is that you can query the MM and get names (from python internal dicts)  and the numerical address on the bus. This can be used for templating. It  also does wishbone so you can hook it up to other stuff.

There is also a "standard" uart (https://github.com/amaranth-lang/amaranth-stdio/blob/main/amaranth_stdio/serial.py). I might give that a bash and check sizes.

Will advise.

**Comment by cbiffle** [comment]
I'd be curious for your results. I didn't use any of the standard stuff, so far, for the following reasons:
1. Wanted to learn Amaranth by doing
2. My current fabric and peripherals are _aggressively_ size-optimized.
3. This processor does not currently have atomic 32-bit bus transactions, which could easily break existing peripherals that assume a 32-bit data bus.

That being said, I'd love to reuse stuff where possible -- as long as it doesn't require too much of a hit to the minimum system size.

**Comment by cbiffle** [comment]
Oh, incidentally, I've checked in my Dhrystone build, if you'd like a larger program to run. (During testing I tried it on the `cpu16` model for the first time, and, uh, I think it's revealed a subtle bug somewhere. Be warned. The `box` model is the more tested of the two.)

**Comment by cbiffle** [comment]
> The link file for the bootloader build is going to suck, I'm going to try to lib.rs it out and have workspaces per target/board with their own link.x file , UART register mapping and a main() that is minimal.

Might be worth noting -- you should only have to do this for the UART and stack pointer. The program itself is position independent and doesn't care where you deposit it. So, that should make the linker script gymnastics easier.

**Comment by zignig** [comment]
MemoryMap is possible.

RAM_WORDS = 256 * 2
[(('bram_1',), 0, 512, None, 16), (('serial', 'UARTTX'), 512, 514, (sig tx), 16), (('serial', 'UARTRX'), 514, 516, (sig rx), 16)]

RAM_WORDS = 256 * 8
[(('bram_1',), 0, 2048, None, 16), (('serial', 'UARTTX'), 2048, 2050, (sig tx), 16), (('serial', 'UARTRX'), 2050, 2052, (sig rx), 16)]

I think it needs to be folded into a component class.

This will add zero LUT as it exists only  in python land.

**Comment by zignig** [comment]
https://github.com/zignig/hapenny/tree/memmap for reference. 

fabric takes the object instead of a  bus , searches for a .map and attaches , it's janky and should all be done in __init__ so you don't have to synthesize to get the map.

**Comment by zignig** [comment]
It works ! , 512 halfwords of memory. 

zignig@bebe:/opt/hapenny/montool$ cargo run  /dev/ttyUSB0 ping

now for more memory.

**Comment by zignig** [comment]
8k + 512b  version , running ... preparing for pull request. Hooray.

**Comment by zignig** [comment]
been tripping TLFT in the outer reaches. PING?
